#run this code to add stuff into your database
#sudo systemctl start mongod
import database 
import random

# adding 30 books into database
database.addNewClass("1", "To Kill a Mockingbird", "Harper Lee", 10) 
database.addNewClass("2", "1984", "George Orwell", 5) 
database.addNewClass("3", "The Great Gatsby", "F. Scott Fitzgerald", 8) 
database.addNewClass("4", "The Catcher in the Rye", "J.D. Salinger", 12) 
database.addNewClass("5", "Pride and Prejudice", "Jane Austen", 7) 
database.addNewClass("6", "The Hobbit", "J.R.R. Tolkien", 9) 
database.addNewClass("7", "The Lord of the Rings", "J.R.R. Tolkien", 6) 
database.addNewClass("8", "Brave New World", "Aldous Huxley", 3) 
database.addNewClass("9", "War and Peace", "Leo Tolstoy", 2) 
database.addNewClass("10", "Moby-Dick", "Herman Melville", 4) 
database.addNewClass("11", "The Odyssey", "Homer", 15) 
database.addNewClass("12", "The Count of Monte Cristo", "Alexandre Dumas", 6) 
database.addNewClass("13", "The Adventures of Sherlock Holmes", "Arthur Conan Doyle", 11) 
database.addNewClass("14", "One Hundred Years of Solitude", "Gabriel Garcia Marquez", 8) 
database.addNewClass("15", "The Grapes of Wrath", "John Steinbeck", 5) 
database.addNewClass("16", "Anna Karenina", "Leo Tolstoy", 7) 
database.addNewClass("17", "The Road", "Cormac McCarthy", 6) 
database.addNewClass("18", "Frankenstein", "Mary Shelley", 4) 
database.addNewClass("19", "The Picture of Dorian Gray", "Oscar Wilde", 5) 
database.addNewClass("20", "The Little Prince", "Antoine de Saint-Exupéry", 9) 
database.addNewClass("21", "Fahrenheit 451", "Ray Bradbury", 6) 
database.addNewClass("22", "The Shining", "Stephen King", 8) 
database.addNewClass("23", "A Tale of Two Cities", "Charles Dickens", 4) 
database.addNewClass("24", "The Alchemist", "Paulo Coelho", 12) 
database.addNewClass("25", "The Brothers Karamazov", "Fyodor Dostoevsky", 5) 
database.addNewClass("26", "Alice's Adventures in Wonderland", "Lewis Carroll", 7) 
database.addNewClass("27", "The Divine Comedy", "Dante Alighieri", 3) 
database.addNewClass("28", "The Chronicles of Narnia", "C.S. Lewis", 10) 
database.addNewClass("29", "The Road Less Traveled", "M. Scott Peck", 6) 
database.addNewClass("30", "Harry Potter and the Sorcerer's Stone", "J.K. Rowling", 15) 

#adding 30 users 
database.addUser("1", "password123", "John Doe")
database.addUser("2", "securePwd456", "Alice Smith")
database.addUser("3", "secretPass", "Ella Johnson")
database.addUser("4", "userPass789", "Michael Wilson")
database.addUser("5", "p@ssw0rd", "Olivia Davis")
database.addUser("6", "realPassword", "James Brown")
database.addUser("7", "P@ssw0rd!", "Sophia White")
database.addUser("8", "12345678", "Emma Martin")
database.addUser("9", "password1234", "William Lee")
database.addUser("10", "secure123!", "Grace Hall")
database.addUser("11", "realPwd567", "Daniel Turner")
database.addUser("12", "P@ssw0rd345", "Lily Clark")
database.addUser("13", "userpass", "Logan Baker")
database.addUser("14", "p@ssword456", "Sophia Wilson")
database.addUser("15", "securepwd789", "Benjamin Anderson")
database.addUser("16", "123456", "Olivia Scott")
database.addUser("17", "pwd123", "Henry Wright")
database.addUser("18", "realuser", "Chloe Young")
database.addUser("19", "password01", "Mason King")
database.addUser("20", "p@ssw0rd99", "Abigail Hill")
database.addUser("21", "pass123", "Ethan Moore")
database.addUser("22", "securepass", "Emily Brown")
database.addUser("23", "user123", "Liam Harris")
database.addUser("24", "P@ssword99", "Ava Mitchell")
database.addUser("25", "realPwd123", "Noah Turner")
database.addUser("26", "secureP@ss", "Sofia Turner")
database.addUser("27", "password567", "Lucas Parker")
database.addUser("28", "1234pass", "Amelia Bell")
database.addUser("29", "pwd999", "William Foster")
database.addUser("30", "p@ssw0rd123", "Mia Carter")

#Adding 1 admin
database.addUser("307","SPA","Saakshi")

#issuing books
for i in range(50):
    bookid = str(random.randint(1,30))
    userid = str(random.randint(1,30))
    # database.issueBook(bookid, userid, "Saakshi", "SPA")
    database.issueBook(bookid, userid)
